services:
  postgres:
    image: postgres
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
